### ISSUE TITLE
Debian Linux on ARM

### ISSUE THREAD

**Issue by renatohcampos** [afontenot/logic2010#1]
I am not sure if this is not possible - due to the ARM architecture - but I was hoping to install Logic 2010 on a series of Raspberry Pi 3 computers running the latest version of Raspbian OS, a Debian-based Linux OS for 64-bit ARM. I downloaded the Logic 2010 master file, made the 'install.sh' file executable, and then ran it. This seemed to install perfectly with no errors. I proceeded to also do both these actions, making executable & running the '.sh' file, to the 'run' file that starts the program. So far I've only been able to produce an error window that says there is a "problem connecting to the database", with the console output stating it "Could not load thread violation checker". Would I have to build Logic 2010 on my own for the Raspberry Pi 3, or is there a workaround to this? I tried messing with Java.jar upon reading from [https://www.reddit.com/r/linux4noobs/comments/36vstx/outdated_logic_2010_linux_guide/] but have not been able to get any further.

**Comment by lmfont** [comment]
Try it again and let me know if it works. There was a temporary problem with the server that has now been fixed.

**Comment by renatohcampos** [comment]
Sorry - it's been a while. Just wanted to update you to let you know it worked! Logic2010 running smoothly on the Raspbian OS.
